### ISSUE TITLE
"It seems that I'm missing some utility files related to 'data'."

### ISSUE THREAD

**Issue by le-wei** [PKU-EPIC/UniDexGrasp#13]
Hello, thank you very much for open-sourcing this excellent framework and providing a large-scale dataset. While studying, I encountered an error message: ImportError: cannot import name 'get_one_shape' from 'algo.pn_utils.maniskill_learn.utils.data'. I've implemented some functions myself, but I'm unsure about how to implement certain functions. It seems that I might be missing some utility files. In order to ensure that the training process is not affected, would it be possible to provide those missing files? Thank you."

**Comment by XYZ-99** [comment]
Thank you for your interest! Try this one #8

**Comment by le-wei** [comment]
"Thank you very much for your quick response, the issue has been resolved."
