### ISSUE TITLE
CSDF ---identifier "CHECK_EQ" is undefined

### ISSUE THREAD

**Issue by le-wei** [PKU-EPIC/UniDexGrasp#14]
Hello, I encountered error when installing CSDF: identifier "CHECK_EQ" is undefined
Error. I used pip install -e . and python setup.py install to install but still failed. Can you help me solve this problem? Or tell me the environment required for compilation. Thank you

**Comment by mzhmxzh** [comment]
Are you using torch 2.x? You could try a lower version of pytorch, such as 1.10.2.

**Comment by le-wei** [comment]
I followed the instructions to configure the virtual environment on the book, using CUDA11.3. There is still this problem, a little do not understand the problem. Thank you very much for your answer

**Comment by le-wei** [comment]
The problem has been resolved by configuring the environment in a new Docker container. The specific reason for the issue is currently unclear.
