### ISSUE TITLE
The error "ValueError: num_samples should be a positive integer value, but got num_samples=0" occurs during data loading.

### ISSUE THREAD

**Issue by le-wei** [PKU-EPIC/UniDexGrasp#15]
When I attempted training, I encountered an error similar to the one in the title. Below is the error message and the directory structure of the project. I suspect there might be an issue with data loading. I appreciate your valuable time; please assist me. Thank you very much.
![error](https://github.com/PKU-EPIC/UniDexGrasp/assets/13995579/d2961bc2-904f-4629-b0b4-f616382a5ea6)
![error1](https://github.com/PKU-EPIC/UniDexGrasp/assets/13995579/b4c2255f-df9b-4212-92d7-477cdec44339)
![error2](https://github.com/PKU-EPIC/UniDexGrasp/assets/13995579/3bd86f23-5545-455a-b24c-31fe8b569461)

**Comment by le-wei** [comment]
I resolved this issue with the help of the information provided at [#3](https://github.com/PKU-EPIC/UniDexGrasp/issues/3.)

**Comment by kangkang2626** [comment]
How to solve this issue?
