### ISSUE TITLE
I have a question about training time

### ISSUE THREAD

**Issue by le-wei** [PKU-EPIC/UniDexGrasp#16]
Hello, I have a question about training time. I'm using an RTX 3080 with 10GB of VRAM for training, and it takes 3 to 6 hours to complete one epoch. Is this correct? Thank you for your response.

![error3](https://github.com/PKU-EPIC/UniDexGrasp/assets/13995579/abcb975d-136e-4f19-a331-dc7d006644b6)

![error4](https://github.com/PKU-EPIC/UniDexGrasp/assets/13995579/590d8d7b-11e7-4604-ba2a-5a07f2c789d9)

**Comment by mzhmxzh** [comment]
May I ask which module you are training? Is it the GraspIPDF or GraspGLOW or ContactNet?
