### ISSUE TITLE
The code for the Dataset Generation

### ISSUE THREAD

**Issue by meihuaz** [PKU-EPIC/UniDexGrasp#17]
Thank you for your excellent work! Can you provide the code for the Dataset Generation?

**Comment by mzhmxzh** [comment]
We used a modified version of DexGraspNet.
The source code is on the `table` branch of its official repository: https://github.com/PKU-EPIC/DexGraspNet/tree/table

**Comment by meihuaz** [comment]
Thank you very much!

**Comment by jianguo-cmd** [comment]
> Thank you very much!

Hello, could you please tell me how to generate a dataset that meets the unidexgrasp format requirements from https://github.com/PKU-EPIC/DexGraspNet/tree/table? For example, the dataset should include files in the format poses/core/******** (object_name) /****.npz, where ****.npz contains plane.npy, qpos.npy, and scale.npy. Running validate_grasps.py from the table will eventually validate the dataset, resulting in a consolidated file named ******** (object_name).npy. Thank you very much!
