### ISSUE TITLE
Question about object data.

### ISSUE THREAD

**Issue by kaijieshi7** [PKU-EPIC/UniDexGrasp#19]
Hi, I have two questions, could you help me to understand them?
1. what's the difference between assets/meshdatav3_pc_feat.zip and assets/meshdatav3_pc_fps.zip.
2. why there is no "apple" or "banana" in the cfg/train_set.yaml, cfg/test_set_seen_cat.yaml and cfg/test_set_unseen_cat.yaml?

**Comment by chord-comic** [comment]
I share the same inquiries.

Additionally, could you kindly make available the _PointNet checkpoint_ capable of reproducing these pc_feat files? This would be immensely helpful for adding new objects to evaluate the algorithm. :)

**Comment by XYZ-99** [comment]
Reference: #25
