### ISSUE TITLE
Questions about data preparation.

### ISSUE THREAD

**Issue by zhengbi-yong** [PKU-EPIC/UniDexGrasp#24]
There are pc.npy, pcs_table.npy, pcs.npy, poses.npy data in the DFCData dataset, but how to generate them? 
I want to train the model on my own dex hand, so I use DexGraspNet's Table branch to generate the poses in the table scene, and only get one npy file. In order to adapt to the format that UniDexGrasp uses, I write a script to convert the npy data to many npz data, but when I run the ./network/train.py to train a ipdf model, I ran into the problem following:
`FileNotFoundError: [Errno 2] No such file or directory: 'data/DFCData/meshes/core/bottle-1a7ba1f4c892e2da30711cdbdbc73924/pcs_table.npy'`
Could someone help me to tackle this?

**Comment by Yam0214** [comment]
I resolved this issue by renaming the folder as discussed in this [comment](https://github.com/PKU-EPIC/UniDexGrasp/issues/3#issuecomment-1584909845).
