### ISSUE TITLE
Request for PointNet Checkpoint to Facilitate Addition of New Objects

### ISSUE THREAD

**Issue by chord-comic** [PKU-EPIC/UniDexGrasp#25]
Could you kindly make available the PointNet checkpoint that can reproduce the "pc_feat_xxx.npy" files from your training dataset? This would greatly assist in adding new objects for evaluating your excellent algorithm. :)

Additionally, would it be possible for you to share the "pose2plane" code? I've managed to find the "plane2pose" function, but the complementary "pose2plane" would be immensely helpful for my work.

**Comment by ubt0001** [comment]
Hello,

Could you kindly provide some hints on the path to the model checkpoint after extracting the files from the provided link? The link offers extracted features from different object datasets, but it appears to not include the model weights. Is there something I might have missed?

Thank you in advance for your assistance.
