### ISSUE TITLE
error gym

### ISSUE THREAD

**Issue by yiqiaoqingyuyu** [PKU-EPIC/UniDexGrasp#26]
Hi, when run bash script/run_train_ppo_state.sh
...
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
**[Error] [carb.gym.plugin] Graphics is nullptr in GymCreateTextureFromFile**
/home/XXX/UniDexGrasp2/dexgrasp/tasks/shadow_hand_grasp.py:243: DeprecationWarning: an integer is required (got type isaacgym._bindings.linux-x86_64.gym_38.DofDriveMode).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  asset_options.default_dof_drive_mode = gymapi.DOF_MODE_NONE
...

The code can be trained, but there is no GYM interface. Will the Gym interface appear after the code runs?
My conda environment : CUDA11.7，Python3.8，isacc gym preview 4 ...

**Comment by wkwan7** [comment]
https://github.com/PKU-EPIC/UniDexGrasp2/issues/4
