### ISSUE TITLE
About ipdf-loss

### ISSUE THREAD

**Issue by gotochen** [PKU-EPIC/UniDexGrasp#28]
When I run ipdf_train,get a runtime error:only tensors of floating point and complex dtype can require gradients.Or get a Attributeerror:'int'object has no attribute 'backward'.
How can I solve this problem?rewrite the compute_loss function in model.py? 
![image](https://github.com/PKU-EPIC/UniDexGrasp/assets/50523432/07e68d72-cfd2-4af6-a40c-2c17c7586233)
![image](https://github.com/PKU-EPIC/UniDexGrasp/assets/50523432/e19770d7-73f1-4c16-b1dd-c4c48f49a958)

**Comment by XYZ-99** [comment]
It seems the loss type is int whereas it is expected to be a floating point.
You could first check the component of loss to find which one is making the loss an int.
We compute the loss here:
https://github.com/PKU-EPIC/UniDexGrasp/blob/36c9bfcf7cedc987dd15e2384c548e51d5aadc21/dexgrasp_generation/network/models/model.py#L91-L109
Feel free to follow up if the problem isn't clear still.
