### ISSUE TITLE
跑eval.py时出现“已杀死”的问题

### ISSUE THREAD

**Issue by rather1015** [PKU-EPIC/UniDexGrasp#29]
在执行python ./network/eval.py  --config-name eval_config --exp-dir=./eval时，报错“已杀死”，下面三张图片分别是我的报错、文件目录和执行eval.py时的cpu占用率，请问这是硬件问题吗？我的电脑是3070+corei7的配置。
![2024-06-17 23-11-34 的屏幕截图](https://github.com/PKU-EPIC/UniDexGrasp/assets/130117672/40652bf0-2c5b-411b-bb24-17159c4283f1)

![2024-06-17 23-11-27 的屏幕截图](https://github.com/PKU-EPIC/UniDexGrasp/assets/130117672/ddb131bf-60bf-4cb1-bcad-55f35cf9a774)
![2024-06-17 23-10-43 的屏幕截图](https://github.com/PKU-EPIC/UniDexGrasp/assets/130117672/821fe9df-0f55-4446-869f-d7c94611cf5c)

**Comment by rather1015** [comment]
![断点处的代码](https://github.com/PKU-EPIC/UniDexGrasp/assets/130117672/2471a959-8fa1-40e9-89e3-6e5641780c57)
现在能确定是断点处的代码的问题，我的self.device的cuda：0是有效的，但是执行这行代码时cpu占用率特别高，而gpu占用率几乎没有改变，请问是什么原因呢？

**Comment by XYZ-99** [comment]
你好，感谢你提供了这么多信息。我们没有遇到过这个问题，而且常规的报错应该有 Traceback，有点奇怪。这看起来是你在初始化 `PointNetPP` 的时候失败了，建议你进入 `PointNetPP` 里面看一下具体是哪一行出现了这个错误。

**Comment by rather1015** [comment]
> 你好，感谢你提供了这么多信息。我们没有遇到过这个问题，而且常规的报错应该有 Traceback，有点奇怪。这看起来是你在初始化 `PointNetPP` 的时候失败了，建议你进入 `PointNetPP` 里面看一下具体是哪一行出现了这个错误。

请问您的项目可以部署到现实环境中得到不同的grasp吗？

**Comment by jianguo-cmd** [comment]
> ![断点处的代码](https://private-user-images.githubusercontent.com/130117672/341108776-2471a959-8fa1-40e9-89e3-6e5641780c57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzkxNTUsIm5iZiI6MTcyMzYzODg1NSwicGF0aCI6Ii8xMzAxMTc2NzIvMzQxMTA4Nzc2LTI0NzFhOTU5LThmYTEtNDBlOS04OWUzLTZlNTY0MTc4MGM1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMjM0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODBkOTUxY2Y2MGI5NmFkMjAyMjAzZWRmZTJmNGM0ZTU2N2Q3MDE0ODc0YjdjM2Y1NmJkZThkYjU5NzFkZDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KdH_UNX2Cu4Xzymc1CGkgNlS9xyxb-oP8saG47v6hIg) 现在能确定是断点处的代码的问题，我的self.device的cuda：0是有效的，但是执行这行代码时cpu占用率特别高，而gpu占用率几乎没有改变，请问是什么原因呢？

q请问您解决了吗？我也遇到这个问题了

**Comment by jianguo-cmd** [comment]
> 在执行python ./network/eval.py --config-name eval_config --exp-dir=./eval时，报错“已杀死”，下面三张图片分别是我的报错、文件目录和执行eval.py时的cpu占用率，请问这是硬件问题吗？我的电脑是3070+corei7的配置。 ![2024-06-17 23-11-34 的屏幕截图](https://private-user-images.githubusercontent.com/130117672/340357058-40652bf0-2c5b-411b-bb24-17159c4283f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzkyOTMsIm5iZiI6MTcyMzYzODk5MywicGF0aCI6Ii8xMzAxMTc2NzIvMzQwMzU3MDU4LTQwNjUyYmYwLTJjNWItNDExYi1iYjI0LTE3MTU5YzQyODNmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMjM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTYyMmExNDUzZTA5YmY5MTRiYWY4YzVkOTM2YjIxNmZlMWRmODRlYzdkYmQzNTQyNGJiNTZiM2VjZjBiNjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ygG_nBOzv6-gHc882fYphy6C11nhTu6_i-RNt5ErFeQ)
> 
> ![2024-06-17 23-11-27 的屏幕截图](https://private-user-images.githubusercontent.com/130117672/340357095-ddb131bf-60bf-4cb1-bcad-55f35cf9a774.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzkyOTMsIm5iZiI6MTcyMzYzODk5MywicGF0aCI6Ii8xMzAxMTc2NzIvMzQwMzU3MDk1LWRkYjEzMWJmLTYwYmYtNGNiMS1iY2FkLTU1ZjM1Y2Y5YTc3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMjM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTFlNTRlN2NmYTEyYjNjMTdkNGU2Zjc3YzdjZjk5ZGFhMzcyYTUzOTdkZTI2ZWNkMzU0OGZkZmNhYmIxZGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G1rbMNBOgU7N00EWTLM1muq5RLTuKW94RQiDbefcmgw) ![2024-06-17 23-10-43 的屏幕截图](https://private-user-images.githubusercontent.com/130117672/340357137-821fe9df-0f55-4446-869f-d7c94611cf5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzkyOTMsIm5iZiI6MTcyMzYzODk5MywicGF0aCI6Ii8xMzAxMTc2NzIvMzQwMzU3MTM3LTgyMWZlOWRmLTBmNTUtNDQ0Ni04NjlmLWQ3Yzk0NjExY2Y1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMjM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDJiNTJmY2JiNjAzYWNhYzIyNTVlOGJhMjA1YWJlYTU4MDVkNjllZmNkYzM4MGY5MzJjM2ZiNTdiY2EyMTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QAaqpyjD7E8rqPAYu08Hhq1RgxsYftuGSBA041uvEzQ)

请问您解决了吗？我也遇到这个问题

**Comment by hooyahliu** [comment]
eval.py也遇到了kill的问题，但不是在你这个位置。我程序kill有两个原因：
1. [num_works](https://github.com/PKU-EPIC/UniDexGrasp/blob/36c9bfcf7cedc987dd15e2384c548e51d5aadc21/dexgrasp_generation/configs/eval_config.yaml#L51)

config中默认的是1，导致我的程序会在加载数据集时随机kill，改为0后该问题解决，原因未知。

2. [tta加载数据的地方](https://github.com/PKU-EPIC/UniDexGrasp/blob/36c9bfcf7cedc987dd15e2384c548e51d5aadc21/dexgrasp_generation/network/eval.py#L96)

我发现是因为上一步生成的result内存巨大，至少在我这里看到其内存占用超过 110G了，因此内存溢出导致了程序kill。我把result中的数据仅保留十分之一，eval.py能够正常运行并得到最终结果。

**Comment by louxinxiang** [comment]
@hooyahliu 请问您跑完eval.py会生成result.pt文件吗？我看了dexgrasp_generation/tests/visualize_result.py需要result.pt文件进行可视化，但是eval.py的源码并没有生成result.py。

**Comment by hooyahliu** [comment]
> @hooyahliu 请问您跑完eval.py会生成result.pt文件吗？我看了dexgrasp_generation/tests/visualize_result.py需要result.pt文件进行可视化，但是eval.py的源码并没有生成result.py。

我运行源码时候没有生成result.pt这个文件，所以我进行了一些修改。
我在 [eval.py运行结束的位置](https://github.com/PKU-EPIC/UniDexGrasp/blob/36c9bfcf7cedc987dd15e2384c548e51d5aadc21/dexgrasp_generation/network/eval.py#L139)手动添加了保存result.pt的程序

pt_path=log_dir+'/result.pt'

torch.save(result, pt_path)

保存的result.pt能够在dexgrasp_generation/tests/visualize_result.py中使用并将结果可视化，但我训练次数较少，因此可视化结果很差。

**Comment by rather1015** [comment]
> > @hooyahliu 请问您跑完eval.py会生成result.pt文件吗？我看了dexgrasp_generation/tests/visualize_result.py需要result.pt文件进行可视化，但是eval.py的源码并没有生成result.py。
> 
> 我运行源码时候没有生成result.pt这个文件，所以我进行了一些修改。 我在 [eval.py运行结束的位置](https://github.com/PKU-EPIC/UniDexGrasp/blob/36c9bfcf7cedc987dd15e2384c548e51d5aadc21/dexgrasp_generation/network/eval.py#L139)手动添加了保存result.pt的程序
> 
> pt_path=log_dir+'/result.pt'
> 
> torch.save(result, pt_path)
> 
> 保存的result.pt能够在dexgrasp_generation/tests/visualize_result.py中使用并将结果可视化，但我训练次数较少，因此可视化结果很差。

我用作者给的权重做预测保存下来的result，效果也一般

**Comment by hooyahliu** [comment]
> > > @hooyahliu 请问您跑完eval.py会生成result.pt文件吗？我看了dexgrasp_generation/tests/visualize_result.py需要result.pt文件进行可视化，但是eval.py的源码并没有生成result.py。
> > 
> > 
> > 我运行源码时候没有生成result.pt这个文件，所以我进行了一些修改。 我在 [eval.py运行结束的位置](https://github.com/PKU-EPIC/UniDexGrasp/blob/36c9bfcf7cedc987dd15e2384c548e51d5aadc21/dexgrasp_generation/network/eval.py#L139)手动添加了保存result.pt的程序
> > pt_path=log_dir+'/result.pt'
> > torch.save(result, pt_path)
> > 保存的result.pt能够在dexgrasp_generation/tests/visualize_result.py中使用并将结果可视化，但我训练次数较少，因此可视化结果很差。
> 
> 我用作者给的权重做预测保存下来的result，效果也一般

作者的权重我运行出错。可否告知你做了什么修改之后能运行的吗？谢谢~

**Comment by jianguo-cmd** [comment]
> > > > @hooyahliu 请问您跑完eval.py会生成result.pt文件吗？我看了dexgrasp_generation/tests/visualize_result.py需要result.pt文件进行可视化，但是eval.py的源码并没有生成result.py。
> > > 
> > > 
> > > 我运行源码时候没有生成result.pt这个文件，所以我进行了一些修改。 我在 [eval.py运行结束的位置](https://github.com/PKU-EPIC/UniDexGrasp/blob/36c9bfcf7cedc987dd15e2384c548e51d5aadc21/dexgrasp_generation/network/eval.py#L139)手动添加了保存result.pt的程序
> > > pt_path=log_dir+'/result.pt'
> > > torch.save(result, pt_path)
> > > 保存的result.pt能够在dexgrasp_generation/tests/visualize_result.py中使用并将结果可视化，但我训练次数较少，因此可视化结果很差。
> > 
> > 
> > 我用作者给的权重做预测保存下来的result，效果也一般
> 
> 作者的权重我运行出错。可否告知你做了什么修改之后能运行的吗？谢谢~

作者给的权重指的是下载的checkpoint里包含的三个文件吗？你试试https://github.com/PKU-EPIC/UniDexGrasp/issues/12这个里有个下载IPDF的ckpt，替换掉checkpoint里的checkpoint就可以运行了。但是我运行之后又出现了std：：bad allocate和RuntimeError: falseINTERNAL ASSERT FAILED at "..\aten\src\ATen\MapAllocator.cpp":135, please report a bug to PyTorch.cannot allocate memory（12）等问题
