### ISSUE TITLE
 Dataset issues

### ISSUE THREAD

**Issue by czlong24** [PKU-EPIC/UniDexGrasp#3]
During run dexgrasp_ Generation, an error occurred while training GrassIPDF: FileNotFoundError: [Errno 2] No such file or directory: 'data/DFCData/poses/core/browl-530c2d8f55f9e9e8ce364511e87f52b0';FileNotFoundError: [Errno 2] No such file or directory: 'data/DFCData/meshes/core/bowl-d1addad5931dd337713f2e93cbeac35d However, there are no pose or meshes in the DFCData folder in the downloaded dataset. May I ask if there is an error in the code or if the dataset name is incorrect.

**Comment by mzhmxzh** [comment]
The meshdatav3.tar.gz should be extracted and renamed to meshes, the datasetv4.1.tar.gz should be extracted and renamed to poses. We will clarify this in the README files soon.

**Comment by mzhmxzh** [comment]
First, use [generate_object_pose.py](https://github.com/PKU-EPIC/UniDexGrasp/blob/main/dexgrasp_generation/scripts/generate_object_pose.py) to randomly drop the object from a high place for 100 times. 
Nest, use [generate_object_table_pc.py](https://github.com/PKU-EPIC/UniDexGrasp/blob/main/dexgrasp_generation/scripts/generate_object_table_pc.py) to take depth images of the object and table, project them into partial point clouds, then fuse them into a complete point cloud. Furthest point sampling is used to down sample the point cloud to 3000 object points and 1000 table points.

**Comment by lptl** [comment]
looks like the generate_object_pose.py has some error on my machine, so that the progress never moves. 
![image](https://github.com/PKU-EPIC/UniDexGrasp/assets/45854583/7f6dd39c-7eee-4309-acc9-0ad147470365)

**Comment by mzhmxzh** [comment]
I fixed a bug in the newest commit on the main branch. How about now? 
I am also using SAPIEN 1.1.1
Perhaps try running the script with command line argument `--n_cpu 1`. If it still doesn't work, check whether the Vulkan renderer is properly installed.

**Comment by mzhmxzh** [comment]
If that is the case, then I guess it may be because the urdf loader of SAPIEN supports only up to 64 object pieces, and you are trying to load a decomposed object with more than 64 convex pieces.

**Comment by lptl** [comment]
May I ask what kind of system you are using? Or even more exactly, the environment used to run the dexgresp_policy. I am currently using Ubuntu 20.04 and Python 3.7.0 and have the following error:
[Error] [carb.gym.plugin] cudaImportExternalMemory failed on rgbImage buffer with error 999

**Comment by wkwan7** [comment]
> May I ask what kind of system you are using? Or even more exactly, the environment used to run the dexgresp_policy. I am currently using Ubuntu 20.04 and Python 3.7.0 and have the following error: [Error] [carb.gym.plugin] cudaImportExternalMemory failed on rgbImage buffer with error 999

Hi, Ubuntu 20.04 and Python 3.7.0 is OK. It seems something is wrong during the rendering of the simulator. I recommend to
    1.  First make sure IsaacGym is correctly installed. (Ensure that Isaac Gym works on your system by running one of the examples from the issacgym/python/examples directory, like joint_monkey.py)
    2. check Vulkan by `vulkaninfo`, this is crucial if you want to use the visual input in the simulator.

**Comment by lptl** [comment]
Sorry, i have got the information from README.md. I will try preview release 3.

**Comment by wkwan7** [comment]
> Thanks. Both `vulkaninfo` and example can be executed successfully. I am using IsaacGym preview relase 4. Are you also using this version?

Is this error in vision-based policy training, and is state-based policy running properly? Also if you are using a multi-gpu machine, you can try to adjust the graphics_device_id [here](https://github.com/PKU-EPIC/UniDexGrasp/blob/3557738974ef83efcba9b27bde83702a6263b7a8/dexgrasp_policy/dexgrasp/cfg/shadow_hand_random_load_vision.yaml#L1), I know in some multi-gpu machine this may need to be set to a particular device.

**Comment by lptl** [comment]
Thanks. This error happens when running vision-based policy training. And I have only one GPU on my machine. Seems like the error is more about my own environment issue not the code. I also can't run examples/inter_torch.py from isaacgym.

**Comment by zihuuuu** [comment]
When I follow the steps to configure the dexgrasp_generation environment, training GraspIPDF,an error will be reported showing AttributeError: 'int' object has no attribute 'backward',Please ask how to solve this problem
![image](https://github.com/PKU-EPIC/UniDexGrasp/assets/137778660/d5dbabc8-ad93-4184-8d71-e9feb312a3b0)

**Comment by lptl** [comment]
> Thanks. This error happens when running vision-based policy training. And I have only one GPU on my machine. Seems like the error is more about my own environment issue not the code. I also can't run examples/inter_torch.py from isaacgym.

I solved this issue by using `export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`. This command is written inside the troubleshooting of the installation documentation of the isaacgym.

**Comment by mzhmxzh** [comment]
Thanks for pointing out this problem and for solving it! It is fixed in our newest commit. :)

**Comment by jianguo-cmd** [comment]
> it turns out that i can run this successfully without using coard.urdf, ie, using the else branch not the if branch. But for each folder, i have its related `.urdf` file.

Have you solved this issue? I'm encountering the problem where the number of convex hulls is less than 64, but there's a coacd.urdf file in the data_root_path/object_code folder. After entering the if branch, the progress never moves. How did you resolve this?
