### ISSUE TITLE
Pre-trained Checkpoints

### ISSUE THREAD

**Issue by mxllc** [PKU-EPIC/UniDexGrasp#6]
Hi, thank you for sharing such a great piece of work! 
May I ask where I can download the pre-trained checkpoints?

**Comment by mzhmxzh** [comment]
The pre-trained checkpoint for dexgrasp_policy is [in the repo](https://github.com/PKU-EPIC/UniDexGrasp/tree/main/dexgrasp_policy/dexgrasp/example_model). 
And we just uploaded the pre-trained checkpoints for dexgrasp_generation [here](https://mirrors.pku.edu.cn/dl-release/UniDexGrasp_CVPR2023/dexgrasp_generation.zip).

**Comment by mxllc** [comment]
Great thanks!

**Comment by Dingry** [comment]
Hi, I attempted to load the pretrained checkpoint for dexgrasp_generation, but I encountered an issue with mismatched keys for RotationNet, GlowNet, and ContactNet. Could you please advise on how to modify them in order to correctly load these checkpoints?

**Comment by XYZ-99** [comment]
Thank you for your interest in our work! 

Did you encounter problems for all 3 models? And could you provide the details of the error information?

> Hi, I attempted to load the pretrained checkpoint for dexgrasp_generation, but I encountered an issue with mismatched keys for RotationNet, GlowNet, and ContactNet. Could you please advise on how to modify them in order to correctly load these checkpoints?

**Comment by jianguo-cmd** [comment]
> Hi, I attempted to load the pretrained checkpoint for dexgrasp_generation, but I encountered an issue with mismatched keys for RotationNet, GlowNet, and ContactNet. Could you please advise on how to modify them in order to correctly load these checkpoints?



> Hi, I attempted to load the pretrained checkpoint for dexgrasp_generation, but I encountered an issue with mismatched keys for RotationNet, GlowNet, and ContactNet. Could you please advise on how to modify them in order to correctly load these checkpoints?

Hello, did you encounter the issue of mismatched keys while running eval.py? How did you resolve it in the end?
