### ISSUE TITLE
seemed missed a file /algo/pn_utils/maniskill_learn/utils/data 

### ISSUE THREAD

**Issue by Norweig1an** [PKU-EPIC/UniDexGrasp#8]
Cannot execute the script file in policy 
from algo.pn_utils.maniskill_learn.utils.data import is_tuple_of
ModuleNotFoundError: No module named 'algo.pn_utils.maniskill_learn.utils.data'

**Comment by mxllc** [comment]
I have the same problem when I run the following script.
```bash
bash script/run_train_ppo_state.sh
```

**Comment by mxllc** [comment]
I have solved this problem after I download the **data** folder in [ManiSkill-Learn](https://github.com/haosulab/ManiSkill-Learn/tree/6ccff87b6e6def8d0c3938cd20d3136a964be160/mani_skill_learn/utils/data).
I hope it can be helpful to you.
